### ISSUE TITLE
Feature Request: Add in options/flags to omit remotes

### ISSUE THREAD

**Issue by jwu910** [a-camarillo/broom#13]
### Description
As a user with a large shared repository, the `origin/*` branches are crowding my list without any way to filter them right now. 

Would you consider adding in an option to delete local repository branches only and/or specify if we want to include remote branches of the same name on a specified remote?

**Comment by a-camarillo** [comment]
Thanks for the feature request @jwu910, I'm currently working on building out more CLI-like functionality and will look first at being able to pass in an `--omit-remotes` like flag to tackle this issue.

**Comment by jwu910** [comment]
I think that sounds great, either omit by default or include by default, but allowing users to set an option that persists could cover many use cases
